keyword_prompt: >
  You are an expert at extracting keywords from scientific texts. Analyze the following abstract and return a list in range(4-8) of most relevant keywords and topics. The output must be a JSON list of lowercased strings, return only the list of strings, with no additional text.
  ABSTRACT:
