keyword_prompt: >
  You are an expert at extracting keywords from scientific texts. Analyze the following abstract and return a list in range(4-8) of most relevant keywords and topics. The output must be a JSON list of lowercased strings, return only the list of strings, with no additional text.
  ABSTRACT:

reference_prompt: >
  You are an expert at extracting references from Arxiv scientific texts. Analyze the following content and return a list of all references cited in the text. The output must be a JSON list of strings, return only the list of strings, with no additional text, extracting only Arxiv references.
  CONTENT: